//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Exchange_Permission = new HashSet<Exchange_Permission>();
        }
    
        public int C_ID { get; set; }
        public string C_Email { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> C_Phone { get; set; }
        public Nullable<int> C_Mob { get; set; }
        public Nullable<int> C_Fax { get; set; }
        public string C_Website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchange_Permission> Exchange_Permission { get; set; }
    }
}
