//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply_Permission()
        {
            this.Supply_Quantity = new HashSet<Supply_Quantity>();
        }
    
        public int SP_ID { get; set; }
        public int Prod_ID { get; set; }
        public Nullable<int> S_ID { get; set; }
        public string WH_Name { get; set; }
        public Nullable<System.DateTime> SP_Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply_Quantity> Supply_Quantity { get; set; }
    }
}
