//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Quantity
    {
        public int SP_ID { get; set; }
        public int Prod_ID { get; set; }
        public int Supply_Quantity1 { get; set; }
        public Nullable<System.DateTime> Prod_ProdDate { get; set; }
        public Nullable<int> Prod_ExpDuration { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supply_Permission Supply_Permission { get; set; }
    }
}
