//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactProduct
    {
        public int TransactID { get; set; }
        public string FromWH { get; set; }
        public string ToWH { get; set; }
        public Nullable<int> Prod_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> S_ID { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
